"""
Khufra Trading System - Base Strategy
Abstract base class for all per-regime trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

import pandas as pd


@dataclass
class TradeSignal:
    """Signal generated by a strategy."""
    direction: str         # 'long' or 'short'
    entry_price: float
    stop_loss: float
    take_profit: float
    strategy_name: str
    regime: str
    timeframe: str
    reasoning: str
    timestamp: datetime = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.utcnow()

    @property
    def risk_reward(self) -> float:
        if self.direction == "long":
            risk = abs(self.entry_price - self.stop_loss)
            reward = abs(self.take_profit - self.entry_price)
        else:
            risk = abs(self.stop_loss - self.entry_price)
            reward = abs(self.entry_price - self.take_profit)
        return reward / risk if risk > 0 else 0


class BaseStrategy(ABC):
    """Abstract base strategy. Each regime has its own implementation."""

    name: str = "base"
    regime: str = "unknown"

    def __init__(self, config):
        self.config = config

    @abstractmethod
    def generate_signal(
        self,
        df: pd.DataFrame,
        indicators: dict,
        current_price: float,
    ) -> Optional[TradeSignal]:
        """
        Analyze data and generate a trade signal if conditions are met.

        Args:
            df: OHLCV DataFrame
            indicators: Pre-calculated indicators dict
            current_price: Current market price

        Returns:
            TradeSignal if conditions met, None otherwise
        """
        pass

    def _get_atr_stop(self, atr: float, multiplier: float = 1.5) -> float:
        """Calculate ATR-based stop distance."""
        return atr * multiplier
